### ISSUE TITLE
Fork of WP-Photo-Sphere using fork of mistic100's fork of Photo Sphere Viewer

### ISSUE THREAD

**Issue by enlewof** [JeremyHeleine/WP-Photo-Sphere#5]
Hi Mr. Heline,

I wanted to let you know that I love your plugin, but wanted the improvements mistic100 made to your Photo Sphere Viewer so I forked your plugin with a minor rename (currently working title WP Photo Sphere Smooth): https://github.com/enlewof/WP-Photo-Sphere.  I plan on submitting this to the Wordpress plugin directory but plan on giving you majority of the credit since I only really changed the javascript libraries and not too much of the PHP.

**Comment by JeremyHeleine** [comment]
Hi!

No problem, you're free to do whatever you want, that's why I chose this license! Thanks for informing me.
If it is a thing you want to know, I have a huge list of new features/improvements I plan to add to Photo Sphere Viewer, including my own 3D renderer. Currently I just have no time to add them, but new features should arrive in about a month (with WP Photo Sphere following a few days after, as usual).

**Comment by enlewof** [comment]
Cool great to know.  Thanks.
